channels:
- conda-forge
dependencies:
- python=3.10.5
- pip<=25.1.1
- pip:
  - mlflow==2.22.1
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.2.3
  - torch==2.7.1
  - torchvision==0.22.1
name: mlflow-env
